build:
  environment:
    php: '8.0'
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          -
            command: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
            idle_timeout: 600
            coverage:
              file: build/logs/clover.xml
              format: clover

checks:
    php:
        code_rating: true
        duplication: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
