collection: ExifMakerNotes\CanonCustom\PersonalFuncValues
name: CanonCustomPersonalFuncValues
title: 'CanonCustom PersonalFuncValues'
handler: tbd
DOMNode: tbd
format: Short
defaultItemCollection: Tiff\Tag
compiler:
    exiftool:
        g1: CanonCustom
        xpath: "//table[@name='CanonCustom::PersonalFuncValues']/tag"
items:
    1:
        exiftool:
            -
                name: PF1Value
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF1Value'
                desc: 'PF1 Value'
    2:
        exiftool:
            -
                name: PF2Value
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF2Value'
                desc: 'PF2 Value'
    3:
        exiftool:
            -
                name: PF3Value
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF3Value'
                desc: 'PF3 Value'
    4:
        exiftool:
            -
                name: PF4ExposureTimeMin
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF4ExposureTimeMin'
                desc: 'PF4 Exposure Time Min'
    5:
        exiftool:
            -
                name: PF4ExposureTimeMax
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF4ExposureTimeMax'
                desc: 'PF4 Exposure Time Max'
    6:
        exiftool:
            -
                name: PF5ApertureMin
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF5ApertureMin'
                desc: 'PF5 Aperture Min'
    7:
        exiftool:
            -
                name: PF5ApertureMax
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF5ApertureMax'
                desc: 'PF5 Aperture Max'
    8:
        exiftool:
            -
                name: PF8BracketShots
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF8BracketShots'
                desc: 'PF8 Bracket Shots'
    9:
        exiftool:
            -
                name: PF19ShootingSpeedLow
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF19ShootingSpeedLow'
                desc: 'PF19 Shooting Speed Low'
    10:
        exiftool:
            -
                name: PF19ShootingSpeedHigh
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF19ShootingSpeedHigh'
                desc: 'PF19 Shooting Speed High'
    11:
        exiftool:
            -
                name: PF20MaxContinousShots
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF20MaxContinousShots'
                desc: 'PF20 Max Continous Shots'
    12:
        exiftool:
            -
                name: PF23ShutterButtonTime
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF23ShutterButtonTime'
                desc: 'PF23 Shutter Button Time'
    13:
        exiftool:
            -
                name: PF23FELockTime
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF23FELockTime'
                desc: 'PF23 FE Lock Time'
    14:
        exiftool:
            -
                name: PF23PostReleaseTime
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF23PostReleaseTime'
                desc: 'PF23 Post Release Time'
    15:
        exiftool:
            -
                name: PF25AEMode
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF25AEMode'
                desc: 'PF25 AE Mode'
    16:
        exiftool:
            -
                name: PF25MeteringMode
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF25MeteringMode'
                desc: 'PF25 Metering Mode'
    17:
        exiftool:
            -
                name: PF25DriveMode
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF25DriveMode'
                desc: 'PF25 Drive Mode'
    18:
        exiftool:
            -
                name: PF25AFMode
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF25AFMode'
                desc: 'PF25 AF Mode'
    19:
        exiftool:
            -
                name: PF25AFPointSel
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF25AFPointSel'
                desc: 'PF25 AF Point Sel'
    20:
        exiftool:
            -
                name: PF25ImageSize
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF25ImageSize'
                desc: 'PF25 Image Size'
    21:
        exiftool:
            -
                name: PF25WBMode
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF25WBMode'
                desc: 'PF25 WB Mode'
    22:
        exiftool:
            -
                name: PF25Parameters
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF25Parameters'
                desc: 'PF25 Parameters'
    23:
        exiftool:
            -
                name: PF25ColorMatrix
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF25ColorMatrix'
                desc: 'PF25 Color Matrix'
    24:
        exiftool:
            -
                name: PF27Value
                type: int16u
                writable: true
                DOMNode: 'CanonCustom:PF27Value'
                desc: 'PF27 Value'
