collection: ExifMakerNotes\Canon\AFConfig
name: CanonAFConfig
title: 'Canon AF Config'
handler: FileEye\MediaProbe\Block\Index
DOMNode: index
format: Long
hasIndexSize: true
defaultItemCollection: Media\Tiff\Tag
compiler:
    exiftool:
        g1: Canon
        xpath: "//table[@name='Canon::AFConfig']/tag"
items:
    0:
        collection: RawData
        name: indexSize
        format: Long
    1:
        exiftool:
            -
                name: AFConfigTool
                type: int32s
                writable: true
                DOMNode: 'Canon:AFConfigTool'
                desc: 'AF Config Tool'
    2:
        exiftool:
            -
                name: AFTrackingSensitivity
                type: int32s
                writable: true
                DOMNode: 'Canon:AFTrackingSensitivity'
                desc: 'AF Tracking Sensitivity'
    3:
        exiftool:
            -
                name: AFAccelDecelTracking
                type: int32s
                writable: true
                DOMNode: 'Canon:AFAccelDecelTracking'
                desc: 'AF Accel/Decel Tracking'
    4:
        exiftool:
            -
                name: AFPointSwitching
                type: int32s
                writable: true
                DOMNode: 'Canon:AFPointSwitching'
                desc: 'AF Point Switching'
    5:
        exiftool:
            -
                name: AIServoFirstImage
                type: int32s
                writable: true
                DOMNode: 'Canon:AIServoFirstImage'
                desc: 'AI Servo First Image'
                values:
                    - 'Equal Priority'
                    - 'Release Priority'
                    - 'Focus Priority'
    6:
        exiftool:
            -
                name: AIServoSecondImage
                type: int32s
                writable: true
                DOMNode: 'Canon:AIServoSecondImage'
                desc: 'AI Servo Second Image'
                values:
                    - 'Equal Priority'
                    - 'Release Priority'
                    - 'Focus Priority'
                    - 'Release High Priority'
                    - 'Focus High Priority'
    7:
        exiftool:
            -
                name: USMLensElectronicMF
                type: int32s
                writable: true
                DOMNode: 'Canon:USMLensElectronicMF'
                desc: 'USM Lens Electronic MF'
                values:
                    - 'Disable After One-Shot'
                    - 'One-Shot -> Enabled'
                    - 'One-Shot -> Enabled (magnify)'
                    - 'Disable in AF Mode'
            -
                name: USMLensElectronicMF
                type: int32s
                writable: true
                DOMNode: 'Canon:USMLensElectronicMF'
                desc: 'USM Lens Electronic MF'
                values:
                    - 'Enable After AF'
                    - 'Disable After AF'
                    - 'Disable in AF Mode'
    8:
        exiftool:
            -
                name: AFAssistBeam
                type: int32s
                writable: true
                DOMNode: 'Canon:AFAssistBeam'
                desc: 'AF Assist Beam'
                values:
                    - Enable
                    - Disable
                    - 'IR AF Assist Beam Only'
                    - 'LED AF Assist Beam Only'
    9:
        exiftool:
            -
                name: OneShotAFRelease
                type: int32s
                writable: true
                DOMNode: 'Canon:OneShotAFRelease'
                desc: 'One Shot AF Release'
                values:
                    - 'Focus Priority'
                    - 'Release Priority'
    10:
        exiftool:
            -
                name: AutoAFPointSelEOSiTRAF
                type: int32s
                writable: true
                DOMNode: 'Canon:AutoAFPointSelEOSiTRAF'
                desc: 'Auto AF Point Sel EOS iTR AF'
                values:
                    - Enable
                    - Disable
    11:
        exiftool:
            -
                name: LensDriveWhenAFImpossible
                type: int32s
                writable: true
                DOMNode: 'Canon:LensDriveWhenAFImpossible'
                desc: 'Lens Drive When AF Impossible'
                values:
                    - 'Continue Focus Search'
                    - 'Stop Focus Search'
    12:
        exiftool:
            -
                name: SelectAFAreaSelectionMode
                type: int32s
                writable: true
                DOMNode: 'Canon:SelectAFAreaSelectionMode'
                desc: 'Select AF Area Selection Mode'
                values:
                    Bit0: 'Single-point AF'
                    Bit1: Auto
                    Bit2: 'Zone AF'
                    Bit3: 'AF Point Expansion (4 point)'
                    Bit4: 'Spot AF'
                    Bit5: 'AF Point Expansion (8 point)'
    13:
        exiftool:
            -
                name: AFAreaSelectionMethod
                type: int32s
                writable: true
                DOMNode: 'Canon:AFAreaSelectionMethod'
                desc: 'AF Area Selection Method'
                values:
                    - 'M-Fn Button'
                    - 'Main Dial'
    14:
        exiftool:
            -
                name: OrientationLinkedAF
                type: int32s
                writable: true
                DOMNode: 'Canon:OrientationLinkedAF'
                desc: 'Orientation Linked AF'
                values:
                    - 'Same for Vert/Horiz Points'
                    - 'Separate Vert/Horiz Points'
                    - 'Separate Area+Points'
    15:
        exiftool:
            -
                name: ManualAFPointSelPattern
                type: int32s
                writable: true
                DOMNode: 'Canon:ManualAFPointSelPattern'
                desc: 'Manual AF Point Sel Pattern'
                values:
                    - 'Stops at AF Area Edges'
                    - Continuous
    16:
        exiftool:
            -
                name: AFPointDisplayDuringFocus
                type: int32s
                writable: true
                DOMNode: 'Canon:AFPointDisplayDuringFocus'
                desc: 'AF Point Display During Focus'
                values:
                    - 'Selected (constant)'
                    - 'All (constant)'
                    - 'Selected (pre-AF, focused)'
                    - 'Selected (focused)'
                    - Disabled
    17:
        exiftool:
            -
                name: VFDisplayIllumination
                type: int32s
                writable: true
                DOMNode: 'Canon:VFDisplayIllumination'
                desc: 'VF Display Illumination'
                values:
                    - Auto
                    - Enable
                    - Disable
    18:
        exiftool:
            -
                name: AFStatusViewfinder
                type: int32s
                writable: true
                DOMNode: 'Canon:AFStatusViewfinder'
                desc: 'AF Status Viewfinder'
                values:
                    - 'Show in Field of View'
                    - 'Show Outside View'
    19:
        exiftool:
            -
                name: InitialAFPointInServo
                type: int32s
                writable: true
                DOMNode: 'Canon:InitialAFPointInServo'
                desc: 'Initial AF Point In Servo'
                values:
                    - 'Initial AF Point Selected'
                    - 'Manual AF Point'
                    - Auto
    20:
        exiftool:
            -
                name: SubjectToDetect
                type: int32s
                writable: true
                DOMNode: 'Canon:SubjectToDetect'
                desc: 'Subject To Detect'
                values:
                    - None
                    - People
                    - Animals
                    - Vehicles
    24:
        exiftool:
            -
                name: EyeDetection
                type: int32s
                writable: true
                DOMNode: 'Canon:EyeDetection'
                desc: 'Eye Detection'
                values:
                    - 'Off'
                    - 'On'
