name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  php-version:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
    - name: Install PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: "none"
        extensions: "yaml"
        ini-values: "zend.assertions=1"

    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-v3-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-v3-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Pre-flight checks
      run: |
        php bin/fileeye-mediaprobe --version
        # Remove the comment to the lines below during development, to let
        # re-compile the specification PHP file from the YAML files.
        # php bin/fileeye-mediaprobe compile
        # php bin/fileeye-mediaprobe dump tests/media-samples tests/media-dumps

    - name: Image file dumps
      continue-on-error: true
      run: |
        php examples/dump-media.php -d tests/media-samples/image/camera/canon_eos_850d_08.jpg
        php examples/dump-media.php -d tests/media-samples/image/broken/canon-eos-650d.jpg
#        php examples/dump-media.php -d tests/media-samples/image/broken/gh-10-b.jpg
#        php examples/dump-media.php -d tests/media-samples/image/broken/gh-11.jpg
#        php examples/dump-media.php -d tests/media-samples/image/broken/pel-176-RPT200076_03.jpg

    - name: Run test suite
#      continue-on-error: true
      run: vendor/bin/phpunit --color=always --testdox --display-deprecations --display-phpunit-deprecations ./tests

#    - name: Code style test
#      if: ${{ matrix.php-version == 7.4 }}
#      run: ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1

# Remove the comment to the lines below during development, to refresh the
# media file dumps.
#    - name: Update media dumps
#      run: php bin/fileeye-mediaprobe dump tests/media-samples tests/media-dumps

#    - name: Upload media dumps
#      uses: actions/upload-artifact@v3
#      with:
#        name: media-dumps
#        path: tests/media-dumps/**/*.yml

    - name: "Run a static analysis with phpstan/phpstan"
      run: vendor/bin/phpstan analyze
